FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY . .

CMD ["uv", "run", "gunicorn", "--chdir", "/app/zaharovo", "-c", "/app/zaharovo/gunicorn.py", "zaharovo.wsgi:application"]
