[project]
name = "main-api"
version = "0.1.0"
description = "Django REST API for online store"
requires-python = ">=3.11"
dependencies = [
  "Django==5.1.7",
  "django-filter==25.1",
  "djangorestframework==3.15.2",
  "djangorestframework-simplejwt==5.5.0",
  "drf-yasg==1.21.10",
  "gunicorn==23.0.0",
  "gevent==25.5.1",
  "pillow==11.1.0",
  "psycopg2-binary==2.9.10",
  "python-dotenv==1.1.0",
  "transliterate==1.10.2",
  "faker==37.3.0",
]

[dependency-groups]
dev = [
  "ruff==0.11.9",
  "pytest==8.3.5",
  "pytest-django==4.11.1",
]

[tool.ruff]
line-length = 88
target-version = "py311"
